// // Code generated by tsgo. DO NOT EDIT.
package main

/*
#include <stdlib.h>
*/
import "C"

import (
  "github.com/cryptodeal/tsgo/examples/abstract"
)

//export _TestFunc
 func _TestFunc (foo *C.char) C.int {
  _foo := C.GoString(foo)
  _returned_value := C.int(abstract.TestFunc(_foo))
  return _returned_value
}

//export _TestFunc2
 func _TestFunc2 (foo *C.char) number /* float32 */unsafe.Pointer {
  _foo := C.GoString(foo)
  _returned_value := number /* float32 */unsafe.Pointer(abstract.TestFunc2(_foo))
  return _returned_value
}

func main() {} // Required but ignored