// Code generated by tsgo. DO NOT EDIT.
/* eslint-disable */

//////////
// source: author.go

export interface AuthorBookListing {
  author_name: string;
  written_books: Book[] | BookArray;
}

//////////
// source: book.go

export type ISBN = string | null;
export interface Chapter {
  /**
   * Chapter title
   */
  title: string;
  /**
   * The amount of words in this chapter
   */
  number_of_words: number /* uint */;
}
export interface Book {
  book_id: string; // A line comment about BookID that should be kept.
  title: string;
  /**
   * ISBN identifier of the book, null if not known.
   */
  isbn: ISBN;
  genre: 'novel' | 'crime' | 'fantasy';
  chapters: Chapter[] | ChapterArray;
  published_at?: string /* RFC 3339 formatted */;
}
