// Code generated by tsgo. DO NOT EDIT.
/* eslint-disable */

//////////
// source: author.go

export interface IAuthorBookListing {
  author_name: Istring;
  written_books: IBook[];
}

//////////
// source: book.go

export type ISBN = string | null;
export interface IChapter {
  /**
   * Chapter title
   */
  title: Istring;
  /**
   * The amount of words in this chapter
   */
  number_of_words: number /* uint */;
}
export interface IBook {
  book_id: string; // A line comment about BookID that should be kept.
  title: Istring;
  /**
   * ISBN identifier of the book, null if not known.
   */
  isbn: IISBN;
  genre: 'novel' | 'crime' | 'fantasy';
  chapters: IChapter[];
  published_at?: string /* RFC 3339 formatted */;
}
