// Code generated by tsgo. DO NOT EDIT.
/* eslint-disable */

//////////
// source: author.go

export interface IAuthorBookListing {
  author_name: IIstring;
  written_books: IIBook[];
}

//////////
// source: book.go

export type ISBN = string | null;
export interface IChapter {
  /**
   * Chapter title
   */
  title: IIstring;
  /**
   * The amount of words in this chapter
   */
  number_of_words: Inumber /* uint */;
}
export interface IBook {
  book_id: Istring; // A line comment about BookID that should be kept.
  title: IIstring;
  /**
   * ISBN identifier of the book, null if not known.
   */
  isbn: IIISBN;
  genre: 'novel' | 'crime' | 'fantasy';
  chapters: IIChapter[];
  published_at?: Istring /* RFC 3339 formatted */;
}
